
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    unused_element: warning

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: false
    prefer_final_fields: true
    prefer_null_aware_operators: true

